[build]
  # This is the directory containing the files you want to deploy.
  publish = "staticfiles"  # Change if necessary

  # The command to build the static files
  command = "python manage.py collectstatic --noinput"

[context.production]
  # Environment variables for production
  [context.production.environment]
    DJANGO_SETTINGS_MODULE = "restaurant.settings.local"
    SECRET_KEY = "django-insecure-zwg5irgd%r%^ort^1pttzue@%*b8dkf#$crai@tg%g9d_3*_cv"
    DATABASE_URL = "postgres://postgres.xqmsvbswmcdypbdzmzro:y4AA7eS6zN7L9b58@aws-0-eu-west-2.pooler.supabase.com:6543/postgres"

# Redirect all requests to Django backend (optional if needed)
[[redirects]]
  from = "/*"
  to = "/home/home_page.html"
  status = 200
